version: '3.8'
services:
  client:
    image: powclient
    restart: always
    depends_on:
      - server
    environment:
      - SERVER_ADDRESS=http://server:3333
      - GC_COUNT=120
  
  server:
    image: powserver
    restart: always
    environment:
      - SERVER_PORT=3333
      - LEVEL_CAP=10
      - POW_DATA=Wisdom
      - TS_EXPIRE_SEC=300